```{r setup, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, 
                      message = FALSE, 
                      fig.align = "center")
```

```{r load-packages, echo = F}
library(tidyverse)
library(knitr)
library(broom)
library(patchwork)
library(haven)
library(yardstick)
library(naniar)
```

```{r}
Wave1_data <- read_sav("Wave1_20170906.sav")
Wave1_data$index <- 1:nrow(Wave1_data)

predictors <- select(Wave1_data, c(country, level3, se002:se012a, se014:pgnum, index))
```

```{r}
ideology_responses <- Wave1_data %>%
  select(index, q121:q148)
```

```{r}
ideology_responses[is.na(ideology_responses)] <- 100000000
```

```{r}
na_sum <- ideology_responses %>%
  mutate(sum = rowSums(ideology_responses[])) %>%
  filter(sum <299999999)

na_sum[na_sum > 100000] <- NA

na_sum$avg <- rowMeans(subset(na_sum, select = c(q121:q148)), na.rm = TRUE)

average_ideology <- select(na_sum, c(index, avg))
```

```{r}
clean_data <- inner_join(average_ideology, predictors, by = "index")
```

### Mutate predictors

```{r}
final_data <- clean_data
final_data$gender <- clean_data$se002 - 1
final_data$marital_status <- clean_data$se004a - 1
final_data$urban_rural <- clean_data$level3 - 1
final_data$age <- clean_data$se003a
final_data$education <- clean_data$se005a
```


```{r country}
clean_data1 <- clean_data %>%
  mutate()
  mutate(case_when(country == 1 ~"Japan", country == 2 ~ "Hong Kong", country == 3 ~ "Korea", country == 4 ~ "China", country == 5 ~ "Mongolia", country == 6 ~ "Philippines", country == 7 ~ "Taiwan", country == 8 ~ "Thailand")) %>% 
  mutate(urban_rural = as.factor(level3)) %>%
  mutate(gender = as.factor(se002 - 1)) %>%
  mutate(age = se003a) %>%
  mutate(marital_status = se004a - 1) %>%
  mutate(education = se005a) %>%
  mutate(religion = as.factor(se006)) %>%
  mutate(case_when(se006 == 1 ~"Shinto", se006 == 2 ~ "Daoism", se006 == 3 ~ "Other Folk Religions", se006 == 4 ~ "Born Again", se006 == 5 ~ "Buddhism", se006 == 6 ~ "Hinduism", se006 == 7 ~ "Islam", se006 == 8 ~ "Roman Catholics", se006 == 9 ~ "Protestantism", se006 == 10 ~ "Others", se006 == 11 ~ "None")) 
```
```{r}
clean_data1 %>%
  count(country)
```

```{r}
clean_data1 <- clean_data %>%
  mutate(religion = as.character(se006)) %>%
  mutate(religion = factor(se006, levels = c("Shinto", "Daoism", "Other Folk Religions",
                           "Born Again",
                           "Buddhism", "Hinduism", "Islam", "Roman Catholics",
                           "Protestantism", "Others", "None")))

```

```{r model}
model <- lm(avg ~ gender + marital_status + age + education + urban_rural, final_data) %>%
  tidy() %>%
  kable(digits = 3)
model
```