```{r setup, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, 
                      message = FALSE, 
                      fig.align = "center")
```

```{r load-packages, echo = F}
library(tidyverse)
library(knitr)
library(broom)
library(patchwork)
library(haven)
library(yardstick)
library(naniar)
library(ggpubr)
library(corrplot)
```

```{r}
Wave1_data <- read_sav("Wave1_20170906.sav")
Wave1_data$index <- 1:nrow(Wave1_data)

predictors <- select(Wave1_data, c(country, level3, se002:se012a, se014:pgnum, index))
```

```{r}
ideology_responses <- Wave1_data %>%
  select(index, q121:q148)
```

```{r}
ideology_responses[is.na(ideology_responses)] <- 100000000
```

```{r}
na_sum <- ideology_responses %>%
  mutate(sum = rowSums(ideology_responses[])) %>%
  filter(sum <299999999)

na_sum[na_sum > 100000] <- NA
```

```{r}
cleaned_ideology1 <- na_sum[, -31]
cleaned_ideology <- cleaned_ideology1[, -1]
```

```{r}
var_iqrs <- as.data.frame(sapply(cleaned_ideology, FUN = IQR, na.rm = TRUE))
var_median <- as.data.frame(sapply(cleaned_ideology, FUN = median, na.rm = TRUE))
var_total <- var_iqrs
var_total$median <- var_median
```

```{r}
```

```{r}
final_cleaned_ideology1 <- cleaned_ideology[, -3]
final_cleaned_ideology2 <- final_cleaned_ideology1[, -4]
final_cleaned_ideology <- final_cleaned_ideology2[, -26]
```

```{r}
corr_ideology <- cor(final_cleaned_ideology, method = c("spearman"), use = "complete.obs")
corrplot(corr_ideology)
```