---
title: "georgie"
author: "gstammer"
date: "11/6/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages, echo = F}
library(labelled)
library(tidyverse)
library(knitr)
library(broom)
library(patchwork)
library(haven)
library(yardstick)
library(naniar)
library(ggpubr)
library(ggcorrplot)
```

```{r}
library(haven)
Wave1_data <- read_sav("Wave1_20170906.sav")
```

```{r}
data <- Wave1_data %>%
  mutate(country = as.factor(country)) %>%
  mutate(religion = as.factor(se006)) %>%
  mutate(gender = as.factor(se002))

levels(data$country) <- c("Japan", "Hong Kong", "Korea", "China",
                          "Mongolia", "Philippines", "Taiwan", "Thailand")
levels(data$religion) <- c("Shinto", "Daoism", "Other Folk Religions",
                           "Born Again",
                           "Buddhism", "Hinduism", "Islam", "Roman Catholics",
                           "Protestantism", "Others", "None")
levels(data$gender) <- c("Male", "Female")
```


```{r}
data %>%
  ggplot(aes(x = country, fill = religion)) +
  geom_bar(position = "fill")
```

```{r}
data %>%
  ggplot(aes(x = country, fill = gender)) +
  geom_bar(position = "fill")

data %>%
  ggplot(aes(x = religion, fill = gender)) +
  geom_bar(position = "dodge")
```


```{r}
religions <- Wave1_data %>%
  select(country, se006) %>%
  group_by(country, se006) %>%
  count()
```


Enzo data

```{r}
Wave1_data <- read_sav("Wave1_20170906.sav")
Wave1_data$index <- 1:nrow(Wave1_data)

predictors <- select(Wave1_data, c(country, level3, se002:pgnum, index))
```

```{r}
ideology_responses <- Wave1_data %>%
  select(index, q121:q148)
```

```{r}
ideology_responses[is.na(ideology_responses)] <- 100000000
```

```{r}
na_sum <- ideology_responses %>%
  mutate(sum = rowSums(ideology_responses[])) %>%
  filter(sum <299999999)

na_sum[na_sum > 100000] <- NA

na_sum$avg <- rowMeans(subset(na_sum, select = c(q121:q148)), na.rm = TRUE)

average_ideology <- select(na_sum, c(index, avg))
```

```{r}
clean_data <- inner_join(average_ideology, predictors, by = "index")
```

```{r simplifying religion}
clean_religion <- clean_data %>%
  mutate(religion = case_when(se006 == 11 ~ 0,
                            se006 < 11 ~ 1))
```




```{r plot ideologies}
#religion vs avg
clean_data %>%
  ggplot(aes(x = as.factor(se006), y = avg)) +
  geom_violin()

#gender vs avg
clean_data %>%
  ggplot(aes(x = as.factor(se002), y = avg)) +
  geom_violin()

#country vs avg
clean_data %>%
  ggplot(aes(x = as.factor(country), y = avg)) +
  geom_violin()

#age vs avg
clean_data %>%
  ggplot(aes(x = as.factor(se003a), y = avg)) +
  geom_violin()

#marital vs avg
clean_data %>%
  ggplot(aes(x = as.factor(se004a), y = avg)) +
  geom_violin()

#income vs avg
clean_data %>%
  ggplot(aes(x = as.factor(se009), y = avg)) +
  geom_violin()

#job vs avg
clean_data %>%
  ggplot(aes(x = as.factor(se012a), y = avg)) +
  geom_violin()

#urban/rural vs avg
clean_data %>%
  ggplot(aes(x = as.factor(level3), y = avg)) +
  geom_violin()

#education vs avg
clean_data %>%
  ggplot(aes(x = as.factor(se005a), y = avg)) +
  geom_jitter(alpha = 0.2)
```



Question correlations

```{r}
Wave1_data <- read_sav("Wave1_20170906.sav")
Wave1_data$index <- 1:nrow(Wave1_data)

predictors <- select(Wave1_data, c(country, level3, se002:se012a, se014:pgnum, index))


ideology_responses <- Wave1_data %>%
  select(index, q121:q148)


ideology_responses[is.na(ideology_responses)] <- 100000000


na_sum <- ideology_responses %>%
  mutate(sum = rowSums(ideology_responses[])) %>%
  filter(sum <299999999)

na_sum[na_sum > 100000] <- NA


cleaned_ideology1 <- na_sum[, -31]
cleaned_ideology <- cleaned_ideology1[, -1]


#var_iqrs <- as.data.frame(sapply(cleaned_ideology, FUN = IQR, na.rm = TRUE))
#var_median <- as.data.frame(sapply(cleaned_ideology, FUN = median, na.rm = TRUE))
#var_total <- var_iqrs
#var_total$median <- var_median


#final_cleaned_ideology1 <- cleaned_ideology[, -3]
#final_cleaned_ideology2 <- final_cleaned_ideology1[, -4]
#final_cleaned_ideology <- final_cleaned_ideology2[, -26]


corr_ideology <- cor(cleaned_ideology, method = c("spearman"), use = "complete.obs")
```

plot
```{r}
ggcorrplot(corr_ideology, ggtheme = theme_bw(),
           colors = c("#ebbb2a", "white", "#208756")) +
  labs(title = "Correlation between questions")
```



