```{r setup, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, 
                      message = FALSE, 
                      fig.align = "center")
```


```{r load-packages, echo = F}
library(tidyverse)
library(knitr)
library(broom)
library(patchwork)
library(haven)
library(yardstick)
library(naniar)
```

```{r}
Wave1_data <- read_sav("Wave1_20170906.sav")
Wave1_data$index <- 1:nrow(Wave1_data)

predictors <- select(Wave1_data, c(country, level3:pgnum, index))
```

```{r}
p <- predictors %>% 
  unite("se012b", se012bjp:se012bth, na.rm = TRUE)
```

```{r}
ideology_responses <- Wave1_data %>%
  select(index, q121:q148)
```

```{r}
ideology_responses[is.na(ideology_responses)] <- 100000000
```

```{r}
na_sum <- ideology_responses %>%
  mutate(sum = rowSums(ideology_responses[])) %>%
  filter(sum <299999999)

na_sum[na_sum > 100000] <- NA

na_sum$avg <- rowMeans(subset(na_sum, select = c(q121:q148)), na.rm = TRUE)

average_ideology <- select(na_sum, c(index, avg))
```

```{r}
clean_data <- inner_join(average_ideology, predictors, by = "index")
```

### Exploratory Data Analysis

```{r}
clean_data 
```

### Mutate predictors
```{r country}
clean_data1 <- clean_data %>%
  mutate(country = as.factor(country)) %>%
  mutate(urban_rural = as.factor(level3)) %>%
  mutate(gender = as.factor(se002 - 1)) %>%
  mutate(age = se003a) %>%
  mutate(marital_status = se004a - 1) %>%
  mutate(education = se005a) %>%
  mutate(religion = as.factor(se006)) %>%
  mutate(case_when(se006 == 1 ~"Shinto", se006 == 2 ~ "Daoism", se006 == 3 ~ "Other Folk Religions", se006 == 4 ~ "Born Again", se006 == 5 ~ "Buddhism", se006 == 6 ~ "Hinduism", se006 == 7 ~ "Islam", se006 == 8 ~ "Roman Catholics", se006 == 9 ~ "Protestantism", se006 == 10 ~ "Others", se006 == 11 ~ "None")) 

levels(clean_data1$religion) <- c("Shinto", "Daoism", "Other Folk Religions",
                           "Born Again",
                           "Buddhism", "Hinduism", "Islam", "Roman Catholics",
                           "Protestantism", "Others", "None")
levels(clean_data1$country) <- c("Japan", "Hong Kong", "Korea", "China",
                          "Mongolia", "Philippines", "Taiwan", "Thailand")

```
```{r}
clean_data1 %>%
  count(gender)
```
```{r}
final_data %>%
  count(se012a)
```

```{r gender}
clean_data1 <- clean_data %>%
  mutate(gender = as.factor(se002 - 1))
```

```{r age} 
clean_data1 <- clean_data %>%
  mutate(age = se003a)
```

```{r marital status}
clean_data1 <- clean_data %>%
  mutate(marital_status = se004a - 1)
```

```{r education}
clean_data1 <- clean_data %>%
  mutate(education = se005a)
```

```{r}
exists("gender")
```

```{r model}
model <- lm(avg ~ country + gender + age + marital_status + urban_rural + education + religion, clean_data1) %>%
  tidy() %>%
  kable(digits = 3)
model
```
```{r}
final_data <- clean_data %>%
  mutate(country = as.factor(country)) %>%
  mutate(urban_rural = as.factor(level3 - 1)) %>%
  mutate(gender = as.factor(se002 - 1)) %>%
  mutate(age = se003a) %>%
  mutate(marital_status = as.factor(se004a - 1)) %>%
  mutate(education = se005a) %>%
  mutate(household_members = se008a) %>%
  mutate(household_generations = se008b) %>%
  mutate(subjective_status = se017) 

levels(final_data$country) <- c("Japan", "Hong Kong", "Korea", "China",
                          "Mongolia", "Philippines", "Taiwan", "Thailand")
```

```{r model}
model <- lm(avg ~ country + gender + marital_status + urban_rural + education + household_members + household_generations + subjective_status, data = final_data) %>%
  tidy(conf.int = 0.95) %>%
  kable(digits = 3)
model
```

$avg = 2.752 - 0.284(Hong Kong) - 0.198(Korea) - 0.421(China) - 0.315(Mongolia) - 0.258(Philippines) - 0.418(Taiwan) - 0.014(gender) + 0.017(education)$

Based on their low p-values, country, gender, and education are the best predictor variables for understanding the respondant's political leanings and opinions towards authoritarian governments. 

Given that zero is not included in the 95%